### ISSUE TITLE
Try switching Georgia (vs Goudy Old Style) to be explicit first font choice

### ISSUE THREAD

**Issue by FichteFoll** [bitprophet/alabaster#73] opened 2016-02-23 17:34 UTC
I find the typeface to be too thin for continuous pleasant reading and would consider something akin to Georgia (which Flask uses for example) to be better. It's also bigger, but the typeface definitely plays a larger role.

I suggest opening the images in new tabs for optimal viewing (github resized them).

source: http://docs.python-requests.org/en/master/
![2016-02-23_18 31 08](https://cloud.githubusercontent.com/assets/931051/13260521/1c489efc-da5c-11e5-9655-a969e63dd7d7.png)

source: http://flask.pocoo.org/docs/0.10/errorhandling/
![2016-02-23_18 33 45](https://cloud.githubusercontent.com/assets/931051/13260523/1e7abe12-da5c-11e5-9fe0-a4e037acaeef.png)

**Comment by kennethreitz** [comment] 2016-02-25 04:28
You know, on all my machines, I only see this theme with Georgia as the body text. I wasn't aware until recently that others see it this way (on Windows it renders with italics sometimes, for some reason).

Georgia looks much better, and was what I intended the body font to be. I would be +10 to an update. 

<img width="767" alt="screen shot 2016-02-24 at 11 26 55 pm" src="https://cloud.githubusercontent.com/assets/119893/13309846/47d971c0-db4e-11e5-95e9-4122a702c757.png">

**Comment by kennethreitz** [comment] 2016-02-25 04:32
p.s. that's how it's always looked on my machines.

**Comment by FichteFoll** [comment] 2016-02-25 15:01
>I wasn't aware until recently that others don't also see it this way (on Windows it renders with italics sometimes, for some reason). I want to fix this. 

As an addition to this, I had the problem of FireFox choosing the italics variant of Goudy Old Style on my machine. The regular variant was clearly installed on my system and it worked in Chrome. I eventually "fixed" the issue by disabling hardware acceleration on FireFox, but until then the issue was even worse.

**Comment by bitprophet** [comment] 2016-02-26 01:02
I see it as Georgia too, for the record. Also +1 on tweaking things so it's intentionally Georgia by default.

Main problem is backwards compatibility, I wonder how many people *are* seeing Old Goudy and *do* like it.

**Comment by kennethreitz** [comment] 2016-02-26 04:57
@bitprophet I think it's safe for us to consider any users seeing it as Old Goudy now as a bug. In the very unlikely event of user backlash over greatly improved typography and text-legibility, we could cut a release that makes this preference configurable (I'd much prefer not to do that though).

**Comment by FichteFoll** [comment] 2016-02-26 14:00
It already is configurable ([in `conf.py`](https://github.com/bitprophet/alabaster#fonts)). This is really just about the default.

**Comment by bitprophet** [comment] 2016-02-27 20:24
Current font theme conf is https://github.com/bitprophet/alabaster/blob/64aa6ddcc8d3f5c40dfe5b9eca46abdbe5b53a99/alabaster/theme.conf#L65 - so question to me is, should we not only remove the 1st entry (`goudy old style`) but also shift Georgia so it's first? Makes it more explicit that we expect the default view for most users to be Georgia.

I suppose we could leave `minion pro` and `bell mt` in the list at 2nd and 3rd place? Depends a lot on who added them originally and why. Guessing they're from Armin's lineage if Kenneth didn't even know Goudy was in here? :D

**Comment by FichteFoll** [comment] 2016-02-28 20:36
Minion Pro is almost as thin as Goudy Old, so it disqualifies as being on that list entirely as well, imo.

Bell MT works. It's similar to Georgia but a bit smaller (at least for me) and reads nicely.

However, I'm +1 for moving Georgia to the front just because it will mean that more (probably all) people are going to see the text in the same way with the same type face and, also regarding my description of Bell MT, it's much more easier to tweak font size that way.

**Comment by segevfiner** [comment] 2017-05-16 15:17
I'm on Windows 7 SP1 64-bit and Goudy Old Style displays in **italic** (Goudy Old Style Italic) in both the latest Firefox and IE. It displays correctly in Chrome. This makes it quite hard to read and makes emphasis indistinguishable from normal body text.

It would really be nicer if this theme used "safer" fonts or "\@font-face" so that it displays the same in all browsers and operating systems.

**Comment by kennethreitz** [comment] 2017-05-16 15:33
I can confirm that the font is indeed italics on Edge on Windows 10.

**Comment by kennethreitz** [comment] 2017-05-16 15:33
However, it doesn't look bad!

**Comment by bitprophet** [comment] 2017-05-18 23:26
Also we never linked this to #37 which is another font related ticket (about adding webfont support for Garamond which apparently also looks better than Goudy.) Feel like they might be slightly exclusive with each other, needs more examination.

**Comment by hynek** [comment] 2017-11-01 15:49
Ehm this would also fix #100. :)

**Comment by hynek** [comment] 2017-11-07 17:18
May I suggest something like `Palatino, Cambria, Droid Serif, Georgia, serif` if you pull any rugs? :)  That gives you good, readable serif fonts on macOS/iOS, “modern” Windows and Android.  (sorted by conflict likeliness)

**Comment by kennethreitz** [comment] 2017-11-07 17:41
@hynek can you send a screenshot?

**Comment by kennethreitz** [comment] 2017-11-07 17:42
Font names are useless to me, only appearances matter.

**Comment by kennethreitz** [comment] 2017-11-07 17:42
Palatino should not be first, in my opinion. Old Goudy should be preferred before it.

**Comment by kennethreitz** [comment] 2017-11-07 17:42
Palatino looks nice, but is a fallback for a reason.

**Comment by kennethreitz** [comment] 2017-11-07 17:43
It's a bit harsh looking, in comparison to Goudy, which has more of a "hand crafted feel", which the theme intends to convey if possible to reader.

**Comment by kennethreitz** [comment] 2017-11-07 17:45
I vote for leaving things as-is. While not always consistient, we have a nice order preserved at the moment, and different readers get different experiences based on what typefaces they have installed (e.g. how much they value typography). I think there's value in that. 

Uniformity in presentation should not be the goal, is my proposal.

**Comment by kennethreitz** [comment] 2017-11-07 17:46
e.g. The variance in font presentation between machines has always been a *feature* to me, not a bug.

**Comment by kennethreitz** [comment] 2017-11-07 17:49
I have Adobe Creative suite installed, as well as some specific typefaces that @mitsuhiko uses that I use for my keynotes/presentations, so my presentation always looks like this:

![screen shot 2017-11-07 at 12-1 47 33 pm](https://user-images.githubusercontent.com/119893/32508955-f798770a-c3b9-11e7-8497-d8575ec5d3ab.png)

I love this presentation, and when I see it looking otherwise on another machine, I am also thrilled, because it looks nice there as well, and is refreshing.

**Comment by kennethreitz** [comment] 2017-11-07 17:50
I think the proper solution here, if we do want to strive for uniformity, is to rely on a Google Font, which I would chose, for the body of the content. Would anyone be against this?

I'd be happy to take some serious time to select an appropriate typeface that reflects the essence of this theme and everything it represents.

-------------

Or, we leave things as-is.

**Comment by kennethreitz** [comment] 2017-11-07 17:51
I have a deep passion for typography, hence me proposing that I take up the task of selecting a suitable all-encompasing typeface for the theme.

**Comment by kennethreitz** [comment] 2017-11-07 17:54
Two good options, thus far:

- **Alegreya** https://fonts.google.com/specimen/Alegreya
- **Goudy Bookletter** (sound familiar?) https://fonts.google.com/specimen/Goudy+Bookletter+1911

Potentially good options for subtitles:

- **IM Fell English SC** https://fonts.google.com/specimen/IM+Fell+English+SC

**Comment by hynek** [comment] 2017-11-07 17:54
Except it looks like this if you have Goudy installed:

![2017-11-07 at 18 51](https://user-images.githubusercontent.com/41240/32509103-a9696322-c3ec-11e7-8e29-5c9810f6ffde.png)

I’ve solved it by killing the font on my mac but I’m surprised that you don’t seem to care how broken it looks on many machines.

***

I’d also advice against web fonts, they make it a terrible experience if your internet isn’t great.  I spent a month in South Africa and holy shit did I learn to hate them.  Not to say nobody should use them but the default theme for Python docs should be inclusive.

**Comment by kennethreitz** [comment] 2017-11-07 17:55
I propose relying straightly on Gaudy bookletter, from google fonts, and making it uniformly presented across all user experiences.

IM Fell English would be a nice addition, but I'd have to play with it to know for sure. I'll prepare a pull request. @bitprophet your thoughts would be much appreciated.

**Comment by kennethreitz** [comment] 2017-11-07 17:56
@hynek that is only for the first load, though, correct? Then they are cached, and each page load should be near-instant for type, yes?

**Comment by kennethreitz** [comment] 2017-11-07 17:56
If this is true, then I propose we find a Gaudy or similar typeface web font and ship it with the theme itself.

**Comment by kennethreitz** [comment] 2017-11-07 17:56
No relying on external sources.

**Comment by kennethreitz** [comment] 2017-11-07 17:57
One source of truth.

**Comment by kennethreitz** [comment] 2017-11-07 17:58
This italicized version does not occur on my machine — I think we should explore why this is happening, as it may be a simple CSS solution that we need to correct this. 

I remember exploring this in the past, and finding a solution. It's lost on me now, though.

**Comment by kennethreitz** [comment] 2017-11-07 17:59
e.g. uninstalling the typeface is not the proper solution — the solution lies within more proper CSS attributes.

**Comment by kennethreitz** [comment] 2017-11-07 18:00
For I have Goudy Bookletter 1911 installed, and I have not this problem, as well as using latest Safari on latest OSX.

Which Goudy do you use, @hynek?

**Comment by kennethreitz** [comment] 2017-11-07 18:01
Here is my Gaudy Bookletter 1911 (for personal/research purposes use only), which I have always used: http://share.kennethreitz.org/2Z2G1K293r0R/goudy_bookletter_1911.otf

**Comment by kennethreitz** [comment] 2017-11-07 18:01
> This font has been released into the public domain by its author, Barry Schwartz. This applies worldwide.

> In some countries this may not be legally possible; if so:

> Barry Schwartz grants anyone the right to use this work for any purpose, without any conditions, unless such conditions are required by law.

**Comment by kennethreitz** [comment] 2017-11-07 18:02
The real question is, @hynek, where did you get your Gaudy?

**Comment by kennethreitz** [comment] 2017-11-07 18:04
My Gaudy is public domain, and is 40KB in size. Certainly, we can convert it to a web font and embed it within alabaster and get the best of all worlds. 

Palatino as default would ruin this theme's essence. It would be perfectly functional, but that is not the goal of this theme. Typography is the goal of this theme.

**Comment by hynek** [comment] 2017-11-07 18:07
Dunno, if it’s an Adobe font, probably somewhere back with Photoshop?

It looks fine in the fonts app:
![2017-11-07 at 19 04](https://user-images.githubusercontent.com/41240/32509759-9589685a-c3ee-11e7-9728-8fc06c74e45d.png)

My coworker who has the same problem definitely had a PS subscription until recently.

Embedding the font with Alabaster doesn’t solve the problem, that it has to be loaded over the net.  Most parts of the world (Africa, Asia) simply don’t have what we are used to.  And if we don't use a CDN, it even has to be loaded for every, single, doc.

**Comment by kennethreitz** [comment] 2017-11-07 18:07
Here is my public domain Gaudy Bookletter 1911, converted to WOFF: 
[webfontkit-20171107-130639.zip](https://github.com/bitprophet/alabaster/files/1451119/webfontkit-20171107-130639.zip)

Let us embed this within Alabaster, and solve this problem once and for all.

**Comment by kennethreitz** [comment] 2017-11-07 18:08
I believe that 40KB is negligible, and services like read the docs do proper e-tag headings for static assets.

**Comment by kennethreitz** [comment] 2017-11-07 18:09
I may be incorrect in thinking so, but I think this is perfectly appropriate and not doing so over 40KB is making the many suffer for the slight inconvenience of the few.

**Comment by kennethreitz** [comment] 2017-11-07 18:10
Keep in mind, I also embed 1.4MB images on all of my documentation pages, and have received 0 complaints so far for doing so. People with slow connections are patient people, and are used to sub-optimal web experiences. 40KB is going to be relatively fast, even over EDGE.

**Comment by hynek** [comment] 2017-11-07 18:11
Well, *this* ticket was open because Goudy is hard to read so it’s hard to tell which alternative means suffering. :)

**Comment by kennethreitz** [comment] 2017-11-07 18:12
And if read the docs doesn't do e-tags for static assets, I'm sure we can convince them to in a 10 minute conversation :)

I'm pretty confident they do, though.

**Comment by kennethreitz** [comment] 2017-11-07 18:12
Gaudy bookletter 1911, the intended Gaudy is not hard to read. Adobe's is.

**Comment by kennethreitz** [comment] 2017-11-07 18:15
I'm speaking authoritatively because Alabaster is based on my work, as the documentation states. I'm also stating, that if the project desires to continue in that lineage then moving to Palatino would be a step in the wrong direction.

**Comment by kennethreitz** [comment] 2017-11-07 18:23
As a first step, we could fix the font family name in the CSS from "gaudy" to "gaudy bookletter". that would resolve @hynek's problem.

We could then evaluate unifying the user experience later, though embedding a web font or otherwise.

Bear in mind, Sphinx search for a documentation site involves loading a JSON doc far larger than 40KB typically.

**Comment by FichteFoll** [comment] 2017-11-07 18:47
Gaudy bookletter 1911 does indeed look better than the Goudy Old Style screenshot I included in the OP.

![2017-11-07_19-40-23](https://user-images.githubusercontent.com/931051/32511346-d0c35408-c3f3-11e7-8997-8fcc3df7179c.png)

Currently, I have Minion Pro rendering on the requests docs (actually, Minion Pro-Bold because apparently I don't have the regular variant – looks quite bad):

![2017-11-07_19-43-30](https://user-images.githubusercontent.com/931051/32511413-fae29b18-c3f3-11e7-98ea-b7d002081b36.png)

I don't care whether a webfont is provided or not, although reasonable fallbacks must be present. NoScript, for example, blocks webfonts by default.

---

Generally I find sans serif fonts much more pleasant to read on displays due to the limited dpi. I do not have a 4k display and you shouldn't assume everyone to have one.
Have you considered using a sans-serif font instead of serif?

**Comment by bitprophet** [comment] 2017-11-07 19:09
I'm generally in favor of a minimal change first, if we can prove that just tweaking the font names a bit is sufficient to head off the "ew, italics" problem (hopefully via @hynek as guinea pig, I dunno how annoying it is for him to perform the system-level font changes that he is using as workaround!)

Re: web fonts and/or embedded fonts, I'm on the fence (all else equal, I _don't_ want to lessen the experience for mobile or non-US/EU users) though I'll also note that in #37, the typically picky @alex also suggested use of a web font.

----

It *sounds like* the recommended change at this point is, what, sticking `goudy bookletter` in front of `goudy old style`? Perhaps simply replacing the latter with the former?

Might be nice to roll up some (internal, external, doesn't matter) documentation about which fonts in our list are available on what default OS installs and/or via common software packages. Just so users who run into this same "wha? it looks bad!!" issue have some frame of reference.

**Comment by kennethreitz** [comment] 2017-11-07 19:49
+1 to Georgia as being first place.

**Comment by willingc** [comment] 2017-11-08 16:10
Thanks @hynek, @kennethreitz, and @bitprophet for finally helping me figure out why the rendering on Safari was not consistent with what I was seeing on Chrome. I happen to also fall into the "ew" italics. For weeks, it has been bugging me, and now I know why ;-)

P.S. Thanks for your work on the theme too :sunflower:

**Comment by evaryont** [comment] 2017-11-28 21:31
Another "ew, italics" here. For whatever reason Firefox on Windows 10 will prefer the Italics over Regular style Goudy Old Style font, so it's somewhat hard to tell what is supposed to be emphasized in the document or not: https://screenshots.firefox.com/RzQW5iarsVSDEKWC/docs.alerta.io

Love the rest of the theme! (And looks great on Linux, funnily enough.)

**Comment by FichteFoll** [comment] 2017-11-29 00:39
@evaryont as I mentioned above, try disabling hardware acceleration within FF. I'm not sure if this has changed since FF57 since I don't use Windows anymore, but that's what helped me previously.

**Comment by goerz** [comment] 2018-04-24 04:31
I'm still seeing the unreadable italic Goudy Old Style font as in @hynek's screenshot. I have to say, considering that this is now the default Sphinx theme, I'm quite flabbergasted that this issue (and #100, which should not be closed) remains unresolved for multiple years. Not having broken fonts for a large number of users seems like it should be a top priority, even if the broken rendering is somehow "not your fault". If Goudy is known not to work for a significant number of users, it should not be part of any theme!

**Comment by FichteFoll** [comment] 2018-04-24 15:55
Since apparently it doesn't seem like it has been mentioned explicitly before, I'm highly in favor of **removing Goudy Old Style from the font list altogether**. As long as it remains there, the italics rendering (also in #100) is a possibility in case any of the earlier fonts are not available, which disqualifies it from being chosen at all even as a fallback.

Currently, the request docs look so ugly to me (see my latest screenshot) that the next time I need to use them I'll probably end up defining a local style override and have it pick a sans-serif font instead. This isn't entirely your fault, since it's unusual to only have a bold variant of a font face installed, but the fact that it looks so different on many machines *is* your fault because you don't consider compatibility through font availability. Or at least you haven't changed anything in two years since I reported the issue.

**Comment by bitprophet** [comment] 2018-05-15 15:26
Hynek will fold me in two if I don't solve this at sprints and I've been meaning to tackle it anyways.

One issue is that of backwards compat, as mentioned much earlier, but from the historic discussion it sounds like there's almost nobody actually seeing Goudy. I certainly aren't (inspector says I'm getting Georgia) and I consider my install to be relatively mainline (macOS, Chrome, no extra fonts installed, no Adobe apps installed, etc).

So we can definitely go ahead with this in an 0.7.x release. I just gotta reread all this to see what the consensus was on exactly how to do it: just remove Goudy; move Goudy around; choose an alternate Goudy (but also probably move it around); etc.

**Comment by bitprophet** [comment] 2018-05-15 15:28
Also, I do want to say I don't appreciate @FichteFoll's snarky attitude 😛  Yea, it's my fault. Yea I haven't solved it in a few years because it doesn't impact me personally and it still sounds like it affects a minority of users.

You can have your money back if you'd like 😁

**Comment by bitprophet** [comment] 2018-05-15 15:58
Yea sounds like just nuking Goudy is the best way forwards. If we inexplicably get folks complaining that they REALLY WANTED Goudy, they can simply do what everyone impacted by this issue is presumably doing - set their own `font_family` theme option override.

**Comment by willingc** [comment] 2018-05-15 16:03
Thanks @bitprophet. Appreciate your work on this theme. The JupyterHub team loves Alabaster.

**Comment by bitprophet** [comment] 2018-05-15 16:11
Also Hynek continues to whisper in my ear that other fonts in our list are frequently Adobe only. Given the high level of control and infrequent distribution of many fonts, it might make sense to just pare it down to `Georgia, serif`.

And to also alter `head_font_family` to match - I get the original conceit of "have different font for the headers" - but that's Garamond right now which is *another* Adobe-only font face apparently.

**Closed** 2018-05-15 16:41 UTC
Labels: bug, enhancement

**Comment by FichteFoll** [comment] 2018-05-16 12:15
Thanks for looking into this and removing the problematic fonts.

I know I've been a bit snarky in my comment, but it was a conscious decision as I didn't see any other way to motivate you to look into it. (And after reading Kenneth's comments again it felt like I had to stress very explicitly that his proposals do not solve the issue.)
It's an extremely frustrating issue once you are affected by it and I wanted to share the frustration with someone who isn't. I hope you can understand and sorry for resorting to this measure.

**Comment by willingc** [comment] 2018-05-16 13:04
> I know I've been a bit snarky in my comment, but it was a conscious decision as I didn't see any other way to motivate you to look into it.

While I can understand frustration, being snarky, especially as a conscious choice, isn't a thoughtful motivator for volunteer maintainers. At PyCon this year, Brett Cannon gave a wonderful talk about communication between maintainers and users: https://youtu.be/tzFWz5fiVKU?t=49m23s It's worth watching if you haven't seen it.

**Comment by goerz** [comment] 2018-05-16 15:16
@bitprophet Thank you for your great work! I'm sorry for having been unnecessarily harsh on this thread. It wasn't meant as a personal criticism.

**Comment by bitprophet** [comment] 2018-06-19 05:32
Apologies for not actually kicking this out the door once we tackled it at sprints! I just bundled it and all of its "hanging out in master, bored as heck" friends into 0.7.11 and it's on PyPI.

**Comment by hynek** [comment] 2018-06-19 13:41
JFTR https://alabaster.readthedocs.io/en/latest/customization.html#fonts needs to be adapted to the new defaults

**Comment by bitprophet** [comment] 2018-06-19 22:04
Ugh I forgot we repeat a lot of the defaults there. Wonder why I did that, usually I'm severely allergic to that sort of repetition. Thanks @hynek ! Will fix.
